name: CD Pipeline

env:
  APP_NAME: app

on:
  push:
    branches: ["main"]
  workflow_dispatch:
permissions:
  packages: write
  contents: read
jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    steps:
      - name: Execute Remote SSH Commands
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -e
            cd ${{ secrets.VPS_PROJECT_PATH }}
            git pull
            docker compose up --build -d
